#!/usr/bin/env python3
import requests
import sys


if (len(sys.argv) < 2):
    print("Please provide a command: add, list, or complete")
    sys.exit(1)

user = sys.argv[1]
r = {}
try:
    r = requests.get(f"http://api.github.com/users/{user}/events", params={"per_page": 5, "page": 1}, headers={"Accept": "application/vnd.github.v3+json"})
    

except requests.RequestException as e:
    print(f"Error fetching GitHub events for user {user}: {e}")
    sys.exit(1)
    
print(f"5 Most Recent GitHub events for user {user}:")

class Event:
    def __init__(self, event_type, repo_name, created_at):
        self.event_type = event_type
        self.repo_name = repo_name
        self.created_at = created_at

#simple output of user events, including event count, type, and repo name in a readable format
for event in r.json():
    e = Event(event['type'], event['repo']['name'], event['created_at'])
    print(f"{e.created_at}: {e.event_type} in {e.repo_name}")